CREATE VIEW U_H (USER_ID, HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY)
AS SELECT UHOME.USER_ID, C.CITY_NAME, C.STATE_NAME, C.COUNTRY_NAME
FROM USER_HOMETOWN_CITY UHOME
LEFT JOIN CITIES C
ON UHOME.HOMETOWN_CITY_ID = C.CITY_ID;

CREATE VIEW U_C (USER_ID, CURRENT_CITY, CURRENT_STATE, CURRENT_COUNTRY)
AS SELECT UCURR.USER_ID, C.CITY_NAME, C.STATE_NAME, C.COUNTRY_NAME
FROM USER_CURRENT_CITY UCURR
LEFT JOIN CITIES C
ON UCURR.CURRENT_CITY_ID = C.CITY_ID;

CREATE VIEW U_E (USER_ID, INSTITUTION_NAME, PROGRAM_YEAR, PROGRAM_CONCENTRATION, PROGRAM_DEGREE)
AS SELECT E.USER_ID, P.INSTITUTION, E.PROGRAM_YEAR, P.CONCENTRATION, P.DEGREE
FROM EDUCATION E  
LEFT JOIN PROGRAMS P
ON E.PROGRAM_ID = P.PROGRAM_ID;

CREATE VIEW UUH (USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER, HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY)
AS SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH, U.DAY_OF_BIRTH, U.GENDER, H.HOMETOWN_CITY, H.HOMETOWN_STATE, H.HOMETOWN_COUNTRY
FROM USERS U 
LEFT JOIN U_H H
ON U.USER_ID = H.USER_ID;

CREATE VIEW UUHC (USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER, HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY, CURRENT_CITY, CURRENT_STATE, CURRENT_COUNTRY) 
AS SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH, U.DAY_OF_BIRTH, U.GENDER, U.HOMETOWN_CITY, U.HOMETOWN_STATE, U.HOMETOWN_COUNTRY, U_C1.CURRENT_CITY, U_C1.CURRENT_STATE, U_C1.CURRENT_COUNTRY
FROM UUH U
LEFT JOIN U_C U_C1
ON U.USER_ID = U_C1.USER_ID;

CREATE VIEW VIEW_USER_INFORMATION (USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER, CURRENT_CITY, CURRENT_STATE, CURRENT_COUNTRY, HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY, INSTITUTION_NAME, PROGRAM_YEAR, PROGRAM_CONCENTRATION, PROGRAM_DEGREE)
AS SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH, U.DAY_OF_BIRTH, U.GENDER, U.CURRENT_CITY, U.CURRENT_STATE, U.CURRENT_COUNTRY, U.HOMETOWN_CITY, U.HOMETOWN_STATE, U.HOMETOWN_COUNTRY,  U_E1.INSTITUTION_NAME, U_E1.PROGRAM_YEAR, U_E1.PROGRAM_CONCENTRATION, U_E1.PROGRAM_DEGREE 
FROM UUHC U
LEFT JOIN U_E U_E1
ON U.USER_ID = U_E1.USER_ID;

CREATE VIEW VIEW_PHOTO_INFORMATION (ALBUM_ID, OWNER_ID, COVER_PHOTO_ID, ALBUM_NAME, ALBUM_CREATED_TIME, ALBUM_MODIFIED_TIME, ALBUM_LINK, ALBUM_VISIBILITY, PHOTO_ID, PHOTO_CAPTION, PHOTO_CREATED_TIME, PHOTO_MODIFIED_TIME, PHOTO_LINK)
AS SELECT A.ALBUM_ID, A.ALBUM_OWNER_ID, A.COVER_PHOTO_ID, A.ALBUM_NAME, A.ALBUM_CREATED_TIME, A.ALBUM_MODIFIED_TIME, A.ALBUM_LINK, A.ALBUM_VISIBILITY, P.PHOTO_ID, P.PHOTO_CAPTION, P.PHOTO_CREATED_TIME, P.PHOTO_MODIFIED_TIME, P.PHOTO_LINK
FROM ALBUMS A
LEFT JOIN PHOTOS P
ON A.ALBUM_ID = P.ALBUM_ID; 

CREATE VIEW VIEW_ARE_FRIENDS (USER1_ID, USER2_ID)
AS SELECT F.USER1_ID, F.USER2_ID
FROM FRIENDS F;

CREATE VIEW VIEW_TAG_INFORMATION (PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X_COORDINATE, TAG_Y_COORDINATE)
AS SELECT T.TAG_PHOTO_ID, T.TAG_SUBJECT_ID, T.TAG_CREATED_TIME, T.TAG_X, T.TAG_Y
FROM TAGS T;

CREATE VIEW VIEW_EVENT_INFORMATION (EVENT_ID, EVENT_CREATOR_ID, EVENT_NAME, EVENT_TAGLINE, EVENT_DESCRIPTION, EVENT_HOST, EVENT_TYPE, EVENT_SUBTYPE, EVENT_LOCATION, EVENT_CITY, EVENT_STATE, EVENT_COUNTRY, EVENT_START_TIME, EVENT_END_TIME)
AS SELECT E.EVENT_ID, E.EVENT_CREATOR_ID, E.EVENT_NAME, E.EVENT_TAGLINE, E.EVENT_DESCRIPTION, E.EVENT_HOST, E.EVENT_TYPE, E.EVENT_SUBTYPE, E.EVENT_LOCATION, C.CITY_NAME, C.STATE_NAME, C.COUNTRY_NAME, E.EVENT_START_TIME, E.EVENT_END_TIME
FROM USER_EVENTS E
LEFT JOIN CITIES C  
ON E.EVENT_CITY_ID = C.CITY_ID;                                                                          